on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: buildah
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/${{ github.repository }}
        tags: ${{ github.ref }}
        containerfiles: Containerfile
    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.buildah.outputs.image }}
        tags: ${{ steps.buildah.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
