on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable
      env:
        REGISTRY: ghcr.io/${{ github.repository }}
        TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - run: >
        podman login
        --username '${{ github.actor }}'
        --password '${{ github.token }}'
        "${REGISTRY,,}"
    - run: >
        podman build
        --tag "${TAG,,}"
        .
    - run: >
        podman push
        "${TAG,,}"
    - if: ${{ github.ref_name == github.event.repository.default_branch }}
      run: >
        podman tag
        "${TAG,,}"
        "${REGISTRY,,}":latest
        &&
        podman push
        "${REGISTRY,,}":latest
