on:
- push
env:
  REGISTRY: ghcr.io/${{ github.repository }}
  TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: >
        podman login
        --username '${{ github.actor }}'
        --password '${{ github.token }}'
        "${REGISTRY,,}"
    - run: >
        podman build
        --tag "${TAG,,}"
        .
    - run: >
        podman push
        "${TAG,,}"
